language: csharp
mono: none
dotnet: 1.0.0-preview2-1-003177
solution: IC-Open.sln

dist: trusty
sudo: required

branches:
    only:
        - master
        - dev

cache:
    directories:
        - $HOME/.nuget
        - $HOME/.nvm
        - $HOME/.npm
        - $HOME/.cache

script:
    - dotnet restore www User
    - dotnet build www User
    - cd www
    - nvm install 6.9.2
    - npm install -g bower gulp-cli
    - npm install
    - bower install
    - gulp
    - cd ..
